### ISSUE TITLE
Antd version needs to match project antd version

### ISSUE THREAD

**Issue by hannesj** [ant-design/static-style-extract#10]
Currently the package specifies the `antd` version in the dependencies as `^5.3.0`. When using yarn as package manager, when upgrading the `antd` dependency in a project, yarn wants to keep the version previously installed for each dependency and copies the previously installed version to `node_modules` inside `@ant-design/static-style-extract` directory in `node_modules`. This causes two different versions of `antd` to be installed, which makes the themes not work when extracting the css. Instead of the current way of specifying the `antd` dependency, it would be better to put it inside `peerDependencies`, as is suggested in the [documentation](https://classic.yarnpkg.com/lang/en/docs/dependency-types/#toc-peerdependencies).

**Comment by iglv** [comment]
We're looking forward to that, too.

**Comment by kiner-tang** [comment]
Thanks for the feedback. Let me follow up on this.

**Comment by kiner-tang** [comment]
Completed in @ant-design/static-style-extract@1.0.2
